Split signature-generator and Gradle plugin into separate projects
Kotlin/binary-compatibility-validator pull request #124
Opened 2023-03-01 13:50 UTC by aSemy

As part of preparatory refactoring for #88, this PR splits up the signature-generator project and Gradle-plugin into two separate projects.

### Description

Because Gradle plugins must use Gradle's embedded version of Kotlin, splitting up the projects means the BCV Gradle plugin can use the embedded Kotlin, while the signature-generator can use another version of Kotlin.

It also means that the BCV Gradle plugin can use the `kotlin-dsl` plugin, which adds some Gradle specific configuration to help plugin development, but is not necessary in the signature-generator.

Splitting up the projects also helps prepare for using the Gradle Worker API, so when the BCV Gradle plugin runs the signature-generator it can specifically control the dependencies used, and potentially default to `kotlinx-metadata` dependency provided by KGP (if present).

### Summary

- signatures-generator contains the JVM code, and is built using the standard KGP
- gradle-plugin contains only the Gradle Plugin code, and is built using Gradle's embedded-Kotlin
- Configuration between the two projects is shared using convention-plugins
- refactored Maven publication build config

### Dependencies

This PR depends on 

* #122 
* #123

2023-05-01 18:27 UTC, aSemy commented on build.gradle.kts
The configuration in this file was moved to buildSrc convention plugins, so that it could be shared between the two new subprojects as appropriate.

2023-05-01 18:48 UTC, aSemy commented on buildSrc/build.gradle.kts
>      }
Sorry, I know you like removing the unnecessary src/main dirs, but in this case I thought it was extra configuration that didn't really bring much. Given how Gradle can be quite fragile, and how IntelliJ has tenuous support of buildSrc as it is, I thought it was better remove anything not strictly necessary.

2023-06-29 14:16 UTC, qwwdfsad commented
I've asked my colleague to help with the Gradle part, he mentioned the following potential caveats:

1) Compilation with embedded Kotlin might lead to LV/AV issues: e.g. with Gradle 8, embedded Kotlin immediately sets LV 1.8, rendering the plugin unusable with Gradle 6.9+. Probably can be fixed with explicit LV/AV for compilation

2) "the BCV Gradle plugin won’t be able to fetch the signature-generator by default". If I got this right, it's not an issues, because GPP proxies maven central as well

3) It's an open question (and it's unclear whether it's an issue at all) how to compile Gradle plugin against `signatures-generator` built with too new Kotlin version

2023-07-01 07:50 UTC, aSemy commented
> I've asked my colleague to help with the Gradle part, he mentioned the following potential caveats:
> 
> 1. Compilation with embedded Kotlin might lead to LV/AV issues: e.g. with Gradle 8, embedded Kotlin immediately sets LV 1.8, rendering the plugin unusable with Gradle 6.9+. Probably can be fixed with explicit LV/AV for compilation

Gradle Test Kit has been set to use Gradle 7.4.2 and the tests seems to work fine (although I don't really understand how or why...).

https://github.com/Kotlin/binary-compatibility-validator/blob/14bd77cb0406a2866bb6802eb073cd293bd47a06/src/functionalTest/kotlin/kotlinx/validation/api/TestDsl.kt#L34


> 2. "the BCV Gradle plugin won’t be able to fetch the signature-generator by default". If I got this right, it's not an issues, because GPP proxies maven central as well

Ah okay, interesting, thanks! And also, now that I think about it, it has to be the case. Lots of Gradle plugins depend on non-plugin dependencies, and they work fine. BCV depends on the Kotlin stdlib already, and that must come from Maven Central.

> 3. It's an open question (and it's unclear whether it's an issue at all) how to compile Gradle plugin against `signatures-generator` built with too new Kotlin version

Yes, good point. I expect that any problems would be picked up by the Gradle Test Kit test. Also, any further incompatibility problems would be reduced in the future by my plan to use a Gradle Worker to run `signatures-generator` in an isolated classpath.

2023-09-18 14:01 UTC, qwwdfsad requested changes
Thank you, and sorry for the delay!

I gave it one more look, and it seems good in general
I have a few questions and an issue with non-conventional Gradle DSL and Maven Coordinates issue and I think it will be good to go

2023-09-18 14:42 UTC, qwwdfsad commented
Also, if it works for you, could you please update Kotlin to 1.9.0 alongside with this change?

2024-01-12 14:22 UTC, closed without merging