Filter out $EntriesMappings class for Kotlin's 1.9 feature 'Enum entries'
Kotlin/binary-compatibility-validator pull request #144
Opened 2023-06-14 08:26 UTC by fzhinkin

Kotlin compiler generates synthetic class holding EnumEntries starting from 1.9. This change filters out such classes from the API dump.

Closes #141

2023-06-14 08:28 UTC, fzhinkin commented
While the change is trivial, I don't see a way to test it easily.
I verified the behavior in a separate project, but I don't see how to pack it into a unit test that could be merged along with the change. 
Maybe someone has good ideas regarding it?

2023-06-14 08:39 UTC, qwwdfsad commented
Update Kotlin to 1.9.0-Beta will do the trick.
We do ensure compatibility via [`apiVersion`/`languageVersion`](https://kotlinlang.org/docs/compatibility-modes.html) and later even the concern with transitive dependencies will [cease to exist](https://youtrack.jetbrains.com/issue/KT-58999)

2023-07-04 12:31 UTC, fzhinkin commented
Updated to `1.8.20` instead, also removed exclusion of stdlib artifacts (it does nothing when the version of Kotlin from Gradle's classpath is lower, which is the case right now).

2023-07-27 13:13 UTC, fzhinkin commented
ping

2023-08-14 17:35 UTC, qwwdfsad requested changes

2023-08-14 17:35 UTC, qwwdfsad commented on src/main/kotlin/api/AsmMetadataLoading.kt
> +fun ClassNode.isEnumEntriesMappings() = isSynthetic(access) && name.endsWith("\$EntriesMappings")
There are currently no tests that check this behaviour.

You'll need `when` over old Kotlin enum (unlikely it's easy to get one in the robust manner) or any Java one in the code to force `$EntriesMapping` appearance

2023-08-15 09:42 UTC, qwwdfsad commented on src/main/kotlin/api/AsmMetadataLoading.kt
> +fun ClassNode.isEnumEntriesMappings() = isSynthetic(access) && name.endsWith("\$EntriesMappings")
No worries.

There is something suspicious happening:
 
1) IDE highlights `EnumClass.entries` as available only since API version 1.8 (red code, `[UNSUPPORTED_FEATURE]`) even though you clearly set it up
2) For clean builds, everything works as expected
3) For incremental builds (run all tests, change something in `entries.kt`), mappings start being generated even though `entries` member is present

2023-08-15 09:44 UTC, qwwdfsad commented on src/main/kotlin/api/AsmMetadataLoading.kt
> +fun ClassNode.isEnumEntriesMappings() = isSynthetic(access) && name.endsWith("\$EntriesMappings")
I'll proceed with the issue further

2023-08-15 09:45 UTC, qwwdfsad approved these changes

2023-08-15 09:45 UTC, merged