Introduce 'ignoredClasses' configuration to exclude classes by fully …
Kotlin/binary-compatibility-validator pull request #28
Opened 2020-12-01 14:25 UTC by SergejIsbrecht

Fixes #25

Open Points: 
* which code formatter should I use?
* should I move the functional-Tests to a different source-set?

I touched a public API, which is used in Kotlin-STD-Lib. I think the change is breaking (byte-code), but when updating to another version, the calling could must only re-compile against the newest version. It should re-compile without issues, because a default value is provided.

```
@ExternalApi
public fun List<ClassBinarySignature>.filterOutNonPublic(nonPublicPackages: Collection<String> = emptyList(), nonPublicClasses: Collection<String> = emptyList()): List<ClassBinarySignature> {
```

2020-12-03 17:08 UTC, qwwdfsad requested changes
Great work, thanks for your contribution!

I have a few comments, let's address them and it's good to go

2020-12-03 17:08 UTC, qwwdfsad commented on src/functionalTest/kotlin/kotlinx/validation/GradlePluginFuncTest.kt
> +        apiDump = testProjectDir.newFolder("api")
It seems like a lot of ceremonies for the test. It would be much better to have a single test project already in the `resources` folder and use GradleRunner runner against it.

In addition to better readability, it will also significantly simplify writing tests in the future.
Your contribution is valuable as is, so feel free to leave it for me if you don't have enough time

2020-12-03 17:08 UTC, qwwdfsad commented on build.gradle.kts
> +sourceSets {
Could you please elaborate on what's the purpose of a separate source set here?
E.g. why the tests cannot be located in a regular `test` package?

2020-12-03 22:08 UTC, SergejIsbrecht commented on src/main/kotlin/ApiValidationExtension.kt
> +    public var ignoredClasses: MutableSet<String> = HashSet()
Yeah, will do. I somehow forgot.

2020-12-03 22:11 UTC, SergejIsbrecht commented on build.gradle.kts
> +sourceSets {
Well, the Gradle tasks are very slow, therefore the Gradle-Docs suggest, that you create a new SourceSet and run those tests on 'check'. You could get quick feedback via ./gradlew test, because the unit-tests run very fast. If you want to see, whether you broke something in the Gradle-Plugin bootstrapping, you could just run ./gradlew check in order to run the unit-tests and the Gradle-"integTests"

2020-12-03 22:26 UTC, SergejIsbrecht commented on src/functionalTest/kotlin/kotlinx/validation/GradlePluginFuncTest.kt
> +        apiDump = testProjectDir.newFolder("api")
I can do it, if you could explain how you would change it. The thing is, that testing the plugin is only possible with the Gradle-TestKit, which takes some setting up. Let's say you want to check different states of your Plugin. For example verify that ignored classes are excluded from apiDump. If you have no api folder, current implementation will crash, this is probably related to #21 . Therefore you have to make sure, that everything is in place, so the plugin is happy to execute given order. 

I would separate the unit-tests and the integration-Tests, that the plugin does, what it should be. You do not have to re-validate, that your business-logic works as expected in the integration-Tests (Gradle), but you have to make sure, that the plugin does what is has been told (e.g. dump the api, ignore files, ignore packages, does not fail if random error occurs. I would say the integration-tests for Gradle are kind of responsible for testing your "front-end" to your business-logic. Sure, it takes some setting up, but I do not see how this could be reduced.

2020-12-07 08:03 UTC, SergejIsbrecht commented on src/main/kotlin/ApiValidationExtension.kt
> +    public var ignoredClasses: MutableSet<String> = HashSet()
Should I also add an example for kts? I already did, just asking whether this is needed or not, because you can not just use the groovy syntax to configure the plugin in kotlin.

2020-12-07 16:21 UTC, qwwdfsad commented on build.gradle.kts
> +sourceSets {
Ok, thanks for the explanation

2020-12-07 16:22 UTC, qwwdfsad commented on src/main/kotlin/ApiValidationExtension.kt
> +    public var ignoredClasses: MutableSet<String> = HashSet()
Kts addition is very welcomed and definitely won't hurt

2020-12-07 16:36 UTC, qwwdfsad commented on src/functionalTest/kotlin/kotlinx/validation/GradlePluginFuncTest.kt
> +        apiDump = testProjectDir.newFolder("api")
Sure. Please take a look at how it is done in our atomicfu library as an example: https://github.com/Kotlin/kotlinx.atomicfu/commit/3b76f6dd52475b0d82ceb9c6018b990408abb99b

>Sure, it takes some setting up, but I do not see how this could be reduced.

For me, it looks like the following:

1) Let's write a test project as a regular folder structure and put it into the resources
2) The test copies the resources to a temporary directory and invokes `Gradle-TestKit` as it's currently being done
3) If you need to "tweak" the settings of an existing test project (e.g. to change `ApiValidationExtension`), instead of appending raw strings to test files, it can be done in the test project itself by using system properties or env. variable.


The idea is that writing/copy-pasting a small project is much more maintainable as opposed to juggling with raw strings: easy to edit, easy to read, hard to make a mistake (that is easy to when operating string literals). Also, such a structure is very welcoming for new tests: copy-paste the project, tweak its build file and you are already there!

2020-12-15 21:34 UTC, SergejIsbrecht commented on src/functionalTest/kotlin/kotlinx/validation/GradlePluginFuncTest.kt
> +        apiDump = testProjectDir.newFolder("api")
I am currently looking into it. Sorry for the delay, I have been quite busy at work.

2020-12-17 16:44 UTC, qwwdfsad commented on src/functionalTest/kotlin/kotlinx/validation/GradlePluginFuncTest.kt
> +        apiDump = testProjectDir.newFolder("api")
Sure, take your time, thanks for keeping me updated!
DSL looks good to me

2020-12-17 22:52 UTC, SergejIsbrecht commented on src/functionalTest/kotlin/kotlinx/validation/GradlePluginFuncTest.kt
> +        apiDump = testProjectDir.newFolder("api")
Please have a look, I updated the PR according to given DSL. Some comments are missing and some proper error-handling, when the test-API is used not properly, but I think it can be used in order to write further tests.

2020-12-21 14:56 UTC, qwwdfsad approved these changes
Amazing work, thanks!

2020-12-21 14:56 UTC, merged