Use defaultPublishConfig if possible for android modules
Kotlin/binary-compatibility-validator pull request #29
Opened 2020-12-01 16:41 UTC by pavelreiter

I have prepared fix for #24 by adding compileOnly dependency on android gradle plugin (`com.android.tools.build:gradle:3.6.4`) and using android project extension to fetch [defaultPublishConfig](https://google.github.io/android-gradle-dsl/3.4/com.android.build.gradle.BaseExtension.html#com.android.build.gradle.BaseExtension:defaultPublishConfig) as preferred source of `compilationName` match.

2020-12-07 16:50 UTC, qwwdfsad requested changes
Thanks

2020-12-07 16:50 UTC, qwwdfsad commented on src/main/kotlin/BinaryCompatibilityValidatorPlugin.kt
> +            val defaultPublishName = androidBase.defaultPublishConfig ?: "release"
It seems like `defaultPublishConfig` is obsolete and recommended way to publish an application with `maven-publish` plugin is not using it: https://developer.android.com/studio/build/maven-publish-plugin.

I see the alternative solution where the user explicitly states the publication name they want to verify, then, if it's missing, we can lookup `defaultPublishConfig` and then fallback to release. It would be nice to have a test for that. 

The project doesn't have the infrastructure for tests yet (it is coming in #28), so the most valuable contribution would be to just put a bunch of sample Android projects into the resources: with legacy maven plugin, with `maven-publish` and with library flavours and I will take care of the rest.

2021-01-08 15:18 UTC, kingargyle commented
Is there any update on this PR on when it might be addressed.   We are looking at using this for our android applications, but will need not only non-release support but flavor support as well.   Ideally, the apiDump should support something like, apiDumpDebug, apiDumpFlavorDebug, apiDumpRelease, apiDumpFlavorRelease.

2021-01-28 14:54 UTC, pavelreiter commented on src/main/kotlin/BinaryCompatibilityValidatorPlugin.kt
> +            val defaultPublishName = androidBase.defaultPublishConfig ?: "release"
Hi, thanks for the comments.
I will try to look into it and since #28 is merged I will try to include some tests.

2021-12-07 09:57 UTC, SumeraMartin commented
@pavelreiter @qwwdfsad Hi, are you planning to finish this PR? Or do you have any workaround?

2021-12-07 11:44 UTC, pavelreiter commented
Hi, I am afraid that I have went with metalava for now. I will close the PR.

2021-12-07 11:44 UTC, closed without merging

2021-12-08 09:25 UTC, SumeraMartin commented
I found a hacky workaround. Since I'm using flavors only for changes directly in the code `when (BuildConfig.FLAVOR) { ... }` and I don't use flavor-specific resources or classes then I'm disabling flavors in build.gradle.kts in case that apiCheck or apiDump task is being executed and I'm adding buildConfigField for FLAVOR with some dummy value. The code will compile fine, the task will succeed and flavors are still in the use. As I said, it is more hack than the correct solution but it works so far.

```
fun Project.startArgsContains(vararg arguments: String): Boolean {
    val startArgs = project.gradle.startParameter.taskRequests.toString()
    return arguments.any { argument -> startArgs.contains(argument) }
}

android {
    val isKotlinBinaryValidatorTask = project.startArgsContains("apiCheck", "apiDump")

    buildTypes {
        getByName(ProjectSettings.BuildType.DEBUG) {
            ...

            if (isKotlinBinaryValidatorTask) {
                buildConfigField("String", "FLAVOR", "\"dummy\"")
            }
        }
        ...
    }
    
    if (!isKotlinBinaryValidatorTask) {
        flavorDimensions(ProjectSettings.Flavor.DIMENSION)
        productFlavors {
            ...
        }
    }
    ...
}