Fixed multiple jvm targets
Kotlin/binary-compatibility-validator pull request #62
Opened 2021-07-02 14:27 UTC by pdvrieze

This is a rework of the multiple-jvm-targets branch that actually works. The testing is "fixed" and the implementation is fixed. Note that this is not 100% compatible with existing projects as it uses target-specific subdirectories (only for multiplatform projects).

2021-07-05 08:02 UTC, qwwdfsad commented
Thanks! Currently I'm busy with other things, but I'll try to return to this PR by the end of this week

2021-08-30 13:30 UTC, pdvrieze commented
The pull request has been rebased upon 0.7.1

2021-09-08 16:45 UTC, qwwdfsad requested changes
Sorry for the delay!

The build does not pass as the plugin now creates the same task twice for any multiplatform project with a single JVM source set, this definitely should not be the case. In fact, it's impossible to apply it to any multiplatform project

2021-09-08 16:45 UTC, qwwdfsad commented on src/main/kotlin/BinaryCompatibilityValidatorPlugin.kt
> +        else -> "$API_DIR/$name"
It would be nice to keep the BCV compatible and store `jvm` dump in a top-level `api` dir _unless_ there are multiple JVM targets

2021-09-13 08:02 UTC, pdvrieze commented
> Sorry for the delay!
> 
> The build does not pass as the plugin now creates the same task twice for any multiplatform project with a single JVM source set, this definitely should not be the case. In fact, it's impossible to apply it to any multiplatform project

This should be fixed in the new pull request.

2021-10-01 15:07 UTC, qwwdfsad reviewed
Great job, thanks!

Please address few minor comments and then the PR will be ready to go: I will do a few minor stylistic cleanups and will release 0.8.0-RC next week

2021-10-01 15:07 UTC, qwwdfsad commented on src/main/kotlin/BinaryCompatibilityValidatorPlugin.kt
> +    AUTO
AUTO seems to be unused in the code

2021-10-02 21:51 UTC, pdvrieze commented on src/main/kotlin/BinaryCompatibilityValidatorPlugin.kt
> +    AUTO
The idea was to make this user configurable (in the configuration extension), but with the working count provider it is actually not needed anymore. I'll remove it.

2021-10-02 21:51 UTC, pdvrieze commented on build.gradle.kts
> +// Hack (from guidance on gradle forums) needed to handle optional plugin dependencies
Looking it up, there should actually be a better way: https://docs.gradle.org/current/userguide/test_kit.html#sub:test-kit-automatic-classpath-injection (rather than https://docs.gradle.org/2.14/userguide/test_kit.html?_ga=2.33896865.1010618029.1633210343-1565008009.1633210343#sub:test-kit-classpath-injection). I'll try to use the better way.

2021-10-03 14:02 UTC, pdvrieze commented
All three changes have been processed in the latest push. I found a better source for the code, and documented what is happening much better.

2021-10-04 14:52 UTC, qwwdfsad approved these changes
That's a great job, thanks for taking care of it!

2021-10-04 14:56 UTC, merged