Synthetic annotations
Kotlin/binary-compatibility-validator pull request #72
Opened 2021-11-24 09:54 UTC by qwwdfsad

2021-11-30 15:44 UTC, ilya-g commented on build.gradle.kts
> +        languageVersion = "1.6"
Beware that the Kotlin compiler below 1.5 won't be able to compile against classes with such metadata version. This may be a problem for a compiler bundled with Gradle, so the version of the compiler bundled into the minimal supported Gradle version should be considered.

2021-11-30 15:50 UTC, ilya-g commented on src/main/kotlin/api/AsmMetadataLoading.kt
> +fun ClassNode.isSyntheticAnnotationClass() = isSynthetic(access) && name.contains("\$annotationImpl\$")
I don't mind detecting annotation implementation classes this way, but what bothers me is that these classes are public at all. At first sight, being package private would be enough for them.

2021-11-30 18:22 UTC, ilya-g requested changes

2021-11-30 18:22 UTC, ilya-g commented on src/main/kotlin/api/AsmMetadataLoading.kt
> +            && !isSyntheticAnnotationClass()
Turns our that annotation classes can contribute to the public binary API due to potential unrestricted cross-module inlining, at least their constructors.
сс @sandwwraith

2021-12-01 15:28 UTC, qwwdfsad commented on src/main/kotlin/api/AsmMetadataLoading.kt
> +fun ClassNode.isSyntheticAnnotationClass() = isSynthetic(access) && name.contains("\$annotationImpl\$")
They can be declared in `inline` functions and as long as they are synthetic, the compiler doesn't bother with detecting that and just makes it `public` (similarly to SAM-constructors)

2021-12-01 15:38 UTC, qwwdfsad commented on src/main/kotlin/api/AsmMetadataLoading.kt
> +            && !isSyntheticAnnotationClass()
When inlining crossing the module boundaries, the compiler re-creates the class to avoid messing with ABI

2021-12-01 15:47 UTC, qwwdfsad commented on build.gradle.kts
> +        languageVersion = "1.6"
Good point, I've reverted that and applied 1.6.0 LM only to tests

2021-12-06 14:32 UTC, merged