Support reading classes from resulting jar
Kotlin/binary-compatibility-validator pull request #99
Opened 2022-09-28 11:25 UTC by ilya-g

... and allow configuring tasks without link to `ApiValidationExtension`

An example of using manually configured tasks in a project without applying the plugin:
```
plugins {
    id("org.jetbrains.kotlinx.binary-compatibility-validator") version ... apply false
}

tasks {
    val apiBuildDir = file("build/api")
    val apiReferenceDir = file("api")
    val apiBuild by registering(KotlinApiBuildTask::class) {
        outputApiDir = apiBuildDir
        inputJar.value(jar.flatMap { it.archiveFile })
        inputDependencies = files()
    }
    val apiDump by registering(Sync::class) {
        dependsOn(apiBuild)
        from(apiBuildDir)
        into(apiReferenceDir)
    }
    val apiCompare by registering(KotlinApiCompareTask::class) {
        dependsOn(apiBuild)
        compareApiDumps(apiReferenceDir, apiBuildDir)
    }
    check { dependsOn(apiCompare) }
}
```

2022-10-03 17:54 UTC, qwwdfsad requested changes

2022-10-03 17:54 UTC, qwwdfsad commented on src/main/kotlin/BinaryCompatibilityValidatorPlugin.kt
> +    val apiBuild = task<KotlinApiBuildTask>(targetConfig.apiTaskName("Build")) {
Is this change required?

2022-10-05 14:59 UTC, ilya-g commented on src/main/kotlin/BinaryCompatibilityValidatorPlugin.kt
> +    val apiBuild = task<KotlinApiBuildTask>(targetConfig.apiTaskName("Build")) {
Otherwise it would be hard to instantiate standalone tasks, as the extension must always be provided, and it's nowhere to find it when the plugin is not applied. 
An alternative approach would be to make the task try to query the extension from the project or from one of its parent projects, but I'm not sure how good this implicit way would be.

2022-10-05 15:51 UTC, ilya-g commented
Two more questions: 
- what is the purpose of `inputDependencies` property? It seems not used in the task action. Can it be made optional?
- can we make `Project.sourceSets` extension internal? Due to being public, it leaks into client scripts and could cause some mess.

2022-10-05 17:34 UTC, ilya-g commented on src/main/kotlin/KotlinApiCompareTask.kt
> +    fun compareApiDumps(apiReferenceDir: File, apiBuildDir: File) {
Probably we can try this approach: 
- applying bcv plugin creates and configures tasks as it does currently, but then api build task's `inputJar` property can be configured manually, and in that case it takes precedence over `inputClassesDirs` source.

2022-10-10 16:10 UTC, qwwdfsad commented on src/main/kotlin/KotlinApiCompareTask.kt
> +    fun compareApiDumps(apiReferenceDir: File, apiBuildDir: File) {
LGTM.

Could you please both add a test on that and update the README about the usage?

2022-10-10 16:10 UTC, qwwdfsad commented on src/main/kotlin/KotlinApiCompareTask.kt
> +    fun compareApiDumps(apiReferenceDir: File, apiBuildDir: File) {
Also, probably should be `internal`?

2022-10-18 09:07 UTC, qwwdfsad commented
>what is the purpose of inputDependencies property? It seems not used in the task action. Can it be made optional?

Yes, it can be. It is required to manually track compilations output and react on its changes even if the corresponding dependent task hasn't been launched

>can we make Project.sourceSets extension val internal?

Sure

2022-10-18 20:47 UTC, ilya-g commented
I've added a test and a readme section.

I'm going to make the other improvements (e.g. making Project.sourceSets internal) in a further PR.

2022-10-20 13:02 UTC, merged